# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('iddia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=15)),
            ],
            options={
                'db_table': 'DIAS_SEMANA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idjornada', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=10)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=60)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
            ],
            options={
                'db_table': 'JORNADA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JornadaTurno',
            fields=[
                ('idconfig', models.AutoField(primary_key=True, serialize=False)),
                ('idjornada', models.ForeignKey(db_column='IDJORNADA', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Jornada')),
            ],
            options={
                'db_table': 'JORNADA_TURNO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idturno', models.AutoField(primary_key=True, serialize=False)),
                ('horadesde', models.CharField(db_column='HORADESDE', max_length=10)),
                ('horahasta', models.CharField(db_column='HORAHASTA', max_length=10)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('diadesde', models.ForeignKey(db_column='DIADESDE', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dia1_turno_id', to='api.Dias')),
                ('diahasta', models.ForeignKey(db_column='DIAHASTA', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dia2_turno_id', to='api.Dias')),
            ],
            options={
                'db_table': 'TURNO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='jornadaturno',
            name='idturno',
            field=models.ForeignKey(db_column='IDTURNO', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Turno'),
        ),
    ]
